### ISSUE TITLE
Add --ignore functionality

### ISSUE THREAD

**Issue by Wei-J-Huang** [tianlangwu/urlStatusChecker#7]
Hello, I would like to work on your project to add lab 4 functionality, i.e adding ignore URL functionality.

**Comment by tianlangwu** [comment]
sure no problem! I love to see your new feature!

**Comment by Wei-J-Huang** [comment]
Hi, I have added in the feature while still allowing the original features to work, including checking multiple files with -ignore, please add my fork as remote. 

My Fork: https://github.com/Wei-J-Huang/urlStatusChecker.git
Branch Name:  issue-7

Let me know what you think about the updates!

**Comment by tianlangwu** [comment]
can you please check, it is not working properly when I am testing.
Both test1.html and test3.txt has the same contain "<a href="http://s9y.org">http://s9y.org</a>" but it didnt ignore. 
let me know if I did anything wrong?
![Screenshot 2020-10-18 102952](https://user-images.githubusercontent.com/60892464/96370936-8bb49400-112d-11eb-90e8-a4fbda3bdf92.jpg)

**Comment by tianlangwu** [comment]
I figured out why.  Because your solution only checks all the lines startWith "http" and "https". Could you please use regex for that? 
Could you please add those from the instruction as well？ "If the file isn't valid, give an appropriate error message and exit? Otherwise, use the file's URL patterns to test all the URLs being processed, skipping any that match."

And we should treat # as a comment which shouldn't ignore the URLs after '#'.

We can discuss it on Slack or WeChat if you wish. Thanks!

**Comment by Wei-J-Huang** [comment]
Could you let me know your name on slack please? I wasn’t able to find you, thanks.

**Comment by tianlangwu** [comment]
> Could you let me know your name on slack please? I wasn’t able to find you, thanks.

**Comment by tianlangwu** [comment]
I just sent a direct message to you on slack . I am Junyong Liu
